info:
  # Database
  db:
    server: app-db
    driver: org.postgresql.Driver
    url: jdbc:postgresql://${info.db.server}:57234/${spring.application.name}?useSSL=false
    username: ${spring.application.name}
    password: ${spring.application.name}@db

  # Hibernate
  hibernate:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hbm2ddl:
      auto: none
    c3p0:
      max_size: 20
      min_size: 5
      idle_test_period: 900


liquibase:
  change-log: classpath:changelog/master.xml