spring:
  application:
    name: expert
  profiles:
    include: db,zuul

server:
  context-path: /expert
  port: 8808
  max-http-header-size: 16384
  tomcat:
    max-threads: 1000
    max-connections: 20000
    max-http-post-size: 10485760

info:
  app:
    name: ${spring.application.name}
    description: Сервер бэкэнда
    version: 1.0

